// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using practice_system.Data;

#nullable disable

namespace practice_system.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260119044951_InitMacDb")]
    partial class InitMacDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("practice_system.Models.Problems.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<Guid>("SetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SetId", "Order");

                    b.ToTable("Problems");
                });

            modelBuilder.Entity("practice_system.Models.Problems.ProblemResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsAnswer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("Order")
                        .HasColumnType("bigint");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ResultType")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("ProblemId", "Order");

                    b.ToTable("ProblemResults");
                });

            modelBuilder.Entity("practice_system.Models.Problems.ProblemSet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ProblemSets");
                });

            modelBuilder.Entity("practice_system.Models.Problems.UserAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("AnsweredAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProblemSetId")
                        .HasColumnType("char(36)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TextAnswer")
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ProblemId");

                    b.ToTable("UserAnswers");
                });

            modelBuilder.Entity("practice_system.Models.Problems.UserAnswerSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("ProblemResultId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserAnswerId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserAnswerId");

                    b.ToTable("UserAnswerSelections");
                });

            modelBuilder.Entity("practice_system.Models.Users.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleName");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("practice_system.Models.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("practice_system.Models.Users.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("CreateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreateBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTimeOffset>("UpdateAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("UpdateBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
